# Generated by Django 5.0.6 on 2024-06-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_alter_userpost_created_alter_userpost_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='created',
            new_name='crated',
        ),
    ]
