# Generated by Django 5.0.6 on 2024-06-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_rename_created_userpost_crated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='crated',
            new_name='created',
        ),
    ]
